schema_version = "1.3"
artifacts = ["/logs/artifacts/model.patch"]

[task]
name = "openmoss/swe-bench-science-007"
description = "Repair unstable spectral registration for drifted MRS transients"
authors = []
keywords = ["scientific-computing", "software-engineering"]

[metadata]
task_id = "007"
language = "python"
base_commit_hash = "2254ab2ae6194b41487c933039c5f2ea204e5107"

[agent]
network_mode = "no-network"
timeout_sec = 5400.0

[environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-environment-python-task-007:v0.1.2@sha256:235fe08b1b099b5c86bfce489ba2b2e1e2993868e5a678eecfa0c6c4e97462eb"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_007"

[verifier]
network_mode = "no-network"
environment_mode = "separate"
timeout_sec = 1800.0

[verifier.environment]
docker_image = "docker.io/kevinxulearning/swe-bench-science-verifier-python-task-007:v0.1.2@sha256:917114c3ffdb183152bb669276dd99ef7838e7530cbeee0b03f2e33bbe4e949b"
os = "linux"
allow_internet = false
cpus = 2
memory_mb = 8192
storage_mb = 20480
workdir = "/app/task_007"
